#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDC.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DIDIDACHUAN")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertOrderForm(OrderForm instance);
    partial void UpdateOrderForm(OrderForm instance);
    partial void DeleteOrderForm(OrderForm instance);
    partial void InsertShipHandle(ShipHandle instance);
    partial void UpdateShipHandle(ShipHandle instance);
    partial void DeleteShipHandle(ShipHandle instance);
    partial void Insertships(ships instance);
    partial void Updateships(ships instance);
    partial void Deleteships(ships instance);
    partial void InsertorderT(orderT instance);
    partial void UpdateorderT(orderT instance);
    partial void DeleteorderT(orderT instance);
    partial void Insertordernews(ordernews instance);
    partial void Updateordernews(ordernews instance);
    partial void Deleteordernews(ordernews instance);
    partial void Insertusers(users instance);
    partial void Updateusers(users instance);
    partial void Deleteusers(users instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DDDC.DAL.Properties.Settings.Default.DIDIDACHUANConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<OrderForm> OrderForm
		{
			get
			{
				return this.GetTable<OrderForm>();
			}
		}
		
		public System.Data.Linq.Table<ShipHandle> ShipHandle
		{
			get
			{
				return this.GetTable<ShipHandle>();
			}
		}
		
		public System.Data.Linq.Table<ships> ships
		{
			get
			{
				return this.GetTable<ships>();
			}
		}
		
		public System.Data.Linq.Table<orderT> orderT
		{
			get
			{
				return this.GetTable<orderT>();
			}
		}
		
		public System.Data.Linq.Table<ordernews> ordernews
		{
			get
			{
				return this.GetTable<ordernews>();
			}
		}
		
		public System.Data.Linq.Table<users> users
		{
			get
			{
				return this.GetTable<users>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderForm")]
	public partial class OrderForm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OrderID;
		
		private string _OrderNumber;
		
		private System.Nullable<int> _ClientID;
		
		private string _ShipName;
		
		private System.Nullable<int> _ShipID;
		
		private System.Nullable<int> _OwnerID;
		
		private string _OwnerName;
		
		private string _PrePosition;
		
		private string _Destination;
		
		private string _Notes;
		
		private System.Nullable<System.DateTime> _Start_Time;
		
		private System.Nullable<System.DateTime> _End_Time;
		
		private string _Comment;
		
		private string _img;
		
		private string _Distance;
		
		private string _Status;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderIDChanging(int value);
    partial void OnOrderIDChanged();
    partial void OnOrderNumberChanging(string value);
    partial void OnOrderNumberChanged();
    partial void OnClientIDChanging(System.Nullable<int> value);
    partial void OnClientIDChanged();
    partial void OnShipNameChanging(string value);
    partial void OnShipNameChanged();
    partial void OnShipIDChanging(System.Nullable<int> value);
    partial void OnShipIDChanged();
    partial void OnOwnerIDChanging(System.Nullable<int> value);
    partial void OnOwnerIDChanged();
    partial void OnOwnerNameChanging(string value);
    partial void OnOwnerNameChanged();
    partial void OnPrePositionChanging(string value);
    partial void OnPrePositionChanged();
    partial void OnDestinationChanging(string value);
    partial void OnDestinationChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnStart_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStart_TimeChanged();
    partial void OnEnd_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEnd_TimeChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OnDistanceChanging(string value);
    partial void OnDistanceChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public OrderForm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this.OnOrderIDChanging(value);
					this.SendPropertyChanging();
					this._OrderID = value;
					this.SendPropertyChanged("OrderID");
					this.OnOrderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", DbType="NVarChar(50)")]
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this.OnOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._OrderNumber = value;
					this.SendPropertyChanged("OrderNumber");
					this.OnOrderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="Int")]
		public System.Nullable<int> ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this.OnClientIDChanging(value);
					this.SendPropertyChanging();
					this._ClientID = value;
					this.SendPropertyChanged("ClientID");
					this.OnClientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipName", DbType="NVarChar(50)")]
		public string ShipName
		{
			get
			{
				return this._ShipName;
			}
			set
			{
				if ((this._ShipName != value))
				{
					this.OnShipNameChanging(value);
					this.SendPropertyChanging();
					this._ShipName = value;
					this.SendPropertyChanged("ShipName");
					this.OnShipNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipID", DbType="Int")]
		public System.Nullable<int> ShipID
		{
			get
			{
				return this._ShipID;
			}
			set
			{
				if ((this._ShipID != value))
				{
					this.OnShipIDChanging(value);
					this.SendPropertyChanging();
					this._ShipID = value;
					this.SendPropertyChanged("ShipID");
					this.OnShipIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="Int")]
		public System.Nullable<int> OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					this.OnOwnerIDChanging(value);
					this.SendPropertyChanging();
					this._OwnerID = value;
					this.SendPropertyChanged("OwnerID");
					this.OnOwnerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerName", DbType="NVarChar(50)")]
		public string OwnerName
		{
			get
			{
				return this._OwnerName;
			}
			set
			{
				if ((this._OwnerName != value))
				{
					this.OnOwnerNameChanging(value);
					this.SendPropertyChanging();
					this._OwnerName = value;
					this.SendPropertyChanged("OwnerName");
					this.OnOwnerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrePosition", DbType="NVarChar(200)")]
		public string PrePosition
		{
			get
			{
				return this._PrePosition;
			}
			set
			{
				if ((this._PrePosition != value))
				{
					this.OnPrePositionChanging(value);
					this.SendPropertyChanging();
					this._PrePosition = value;
					this.SendPropertyChanged("PrePosition");
					this.OnPrePositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destination", DbType="NVarChar(200)")]
		public string Destination
		{
			get
			{
				return this._Destination;
			}
			set
			{
				if ((this._Destination != value))
				{
					this.OnDestinationChanging(value);
					this.SendPropertyChanging();
					this._Destination = value;
					this.SendPropertyChanged("Destination");
					this.OnDestinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(255)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Start_Time
		{
			get
			{
				return this._Start_Time;
			}
			set
			{
				if ((this._Start_Time != value))
				{
					this.OnStart_TimeChanging(value);
					this.SendPropertyChanging();
					this._Start_Time = value;
					this.SendPropertyChanged("Start_Time");
					this.OnStart_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> End_Time
		{
			get
			{
				return this._End_Time;
			}
			set
			{
				if ((this._End_Time != value))
				{
					this.OnEnd_TimeChanging(value);
					this.SendPropertyChanging();
					this._End_Time = value;
					this.SendPropertyChanged("End_Time");
					this.OnEnd_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(50)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distance", DbType="NVarChar(50)")]
		public string Distance
		{
			get
			{
				return this._Distance;
			}
			set
			{
				if ((this._Distance != value))
				{
					this.OnDistanceChanging(value);
					this.SendPropertyChanging();
					this._Distance = value;
					this.SendPropertyChanged("Distance");
					this.OnDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShipHandle")]
	public partial class ShipHandle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ship_id;
		
		private System.Nullable<int> _owner_id;
		
		private string _ship_name;
		
		private string _ship_type;
		
		private System.Nullable<int> _capacity;
		
		private string _ship_status;
		
		private System.Nullable<System.DateTime> _ship_reg_time;
		
		private string _Picture;
		
		private string _province;
		
		private string _city;
		
		private string _Position;
		
		private string _IsAllowed;
		
		private string _Admin_name;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onship_idChanging(int value);
    partial void Onship_idChanged();
    partial void Onowner_idChanging(System.Nullable<int> value);
    partial void Onowner_idChanged();
    partial void Onship_nameChanging(string value);
    partial void Onship_nameChanged();
    partial void Onship_typeChanging(string value);
    partial void Onship_typeChanged();
    partial void OncapacityChanging(System.Nullable<int> value);
    partial void OncapacityChanged();
    partial void Onship_statusChanging(string value);
    partial void Onship_statusChanged();
    partial void Onship_reg_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onship_reg_timeChanged();
    partial void OnPictureChanging(string value);
    partial void OnPictureChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnIsAllowedChanging(string value);
    partial void OnIsAllowedChanged();
    partial void OnAdmin_nameChanging(string value);
    partial void OnAdmin_nameChanged();
    #endregion
		
		public ShipHandle()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ship_id
		{
			get
			{
				return this._ship_id;
			}
			set
			{
				if ((this._ship_id != value))
				{
					this.Onship_idChanging(value);
					this.SendPropertyChanging();
					this._ship_id = value;
					this.SendPropertyChanged("ship_id");
					this.Onship_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_id", DbType="Int")]
		public System.Nullable<int> owner_id
		{
			get
			{
				return this._owner_id;
			}
			set
			{
				if ((this._owner_id != value))
				{
					this.Onowner_idChanging(value);
					this.SendPropertyChanging();
					this._owner_id = value;
					this.SendPropertyChanged("owner_id");
					this.Onowner_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_name", DbType="NVarChar(50)")]
		public string ship_name
		{
			get
			{
				return this._ship_name;
			}
			set
			{
				if ((this._ship_name != value))
				{
					this.Onship_nameChanging(value);
					this.SendPropertyChanging();
					this._ship_name = value;
					this.SendPropertyChanged("ship_name");
					this.Onship_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_type", DbType="NVarChar(50)")]
		public string ship_type
		{
			get
			{
				return this._ship_type;
			}
			set
			{
				if ((this._ship_type != value))
				{
					this.Onship_typeChanging(value);
					this.SendPropertyChanging();
					this._ship_type = value;
					this.SendPropertyChanged("ship_type");
					this.Onship_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacity", DbType="Int")]
		public System.Nullable<int> capacity
		{
			get
			{
				return this._capacity;
			}
			set
			{
				if ((this._capacity != value))
				{
					this.OncapacityChanging(value);
					this.SendPropertyChanging();
					this._capacity = value;
					this.SendPropertyChanged("capacity");
					this.OncapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_status", DbType="NVarChar(50)")]
		public string ship_status
		{
			get
			{
				return this._ship_status;
			}
			set
			{
				if ((this._ship_status != value))
				{
					this.Onship_statusChanging(value);
					this.SendPropertyChanging();
					this._ship_status = value;
					this.SendPropertyChanged("ship_status");
					this.Onship_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_reg_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> ship_reg_time
		{
			get
			{
				return this._ship_reg_time;
			}
			set
			{
				if ((this._ship_reg_time != value))
				{
					this.Onship_reg_timeChanging(value);
					this.SendPropertyChanging();
					this._ship_reg_time = value;
					this.SendPropertyChanged("ship_reg_time");
					this.Onship_reg_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="NVarChar(200)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="NVarChar(50)")]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(50)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAllowed", DbType="NVarChar(50)")]
		public string IsAllowed
		{
			get
			{
				return this._IsAllowed;
			}
			set
			{
				if ((this._IsAllowed != value))
				{
					this.OnIsAllowedChanging(value);
					this.SendPropertyChanging();
					this._IsAllowed = value;
					this.SendPropertyChanged("IsAllowed");
					this.OnIsAllowedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_name", DbType="NVarChar(50)")]
		public string Admin_name
		{
			get
			{
				return this._Admin_name;
			}
			set
			{
				if ((this._Admin_name != value))
				{
					this.OnAdmin_nameChanging(value);
					this.SendPropertyChanging();
					this._Admin_name = value;
					this.SendPropertyChanged("Admin_name");
					this.OnAdmin_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ships")]
	public partial class ships : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ship_id;
		
		private System.Nullable<int> _owner_id;
		
		private string _ship_name;
		
		private string _ship_type;
		
		private System.Nullable<int> _capacity;
		
		private string _ship_status;
		
		private System.Nullable<System.DateTime> _ship_reg_time;
		
		private string _Picture;
		
		private string _province;
		
		private string _city;
		
		private string _Position;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onship_idChanging(int value);
    partial void Onship_idChanged();
    partial void Onowner_idChanging(System.Nullable<int> value);
    partial void Onowner_idChanged();
    partial void Onship_nameChanging(string value);
    partial void Onship_nameChanged();
    partial void Onship_typeChanging(string value);
    partial void Onship_typeChanged();
    partial void OncapacityChanging(System.Nullable<int> value);
    partial void OncapacityChanged();
    partial void Onship_statusChanging(string value);
    partial void Onship_statusChanged();
    partial void Onship_reg_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onship_reg_timeChanged();
    partial void OnPictureChanging(string value);
    partial void OnPictureChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    #endregion
		
		public ships()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ship_id
		{
			get
			{
				return this._ship_id;
			}
			set
			{
				if ((this._ship_id != value))
				{
					this.Onship_idChanging(value);
					this.SendPropertyChanging();
					this._ship_id = value;
					this.SendPropertyChanged("ship_id");
					this.Onship_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_id", DbType="Int")]
		public System.Nullable<int> owner_id
		{
			get
			{
				return this._owner_id;
			}
			set
			{
				if ((this._owner_id != value))
				{
					this.Onowner_idChanging(value);
					this.SendPropertyChanging();
					this._owner_id = value;
					this.SendPropertyChanged("owner_id");
					this.Onowner_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_name", DbType="NVarChar(50)")]
		public string ship_name
		{
			get
			{
				return this._ship_name;
			}
			set
			{
				if ((this._ship_name != value))
				{
					this.Onship_nameChanging(value);
					this.SendPropertyChanging();
					this._ship_name = value;
					this.SendPropertyChanged("ship_name");
					this.Onship_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_type", DbType="NVarChar(50)")]
		public string ship_type
		{
			get
			{
				return this._ship_type;
			}
			set
			{
				if ((this._ship_type != value))
				{
					this.Onship_typeChanging(value);
					this.SendPropertyChanging();
					this._ship_type = value;
					this.SendPropertyChanged("ship_type");
					this.Onship_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacity", DbType="Int")]
		public System.Nullable<int> capacity
		{
			get
			{
				return this._capacity;
			}
			set
			{
				if ((this._capacity != value))
				{
					this.OncapacityChanging(value);
					this.SendPropertyChanging();
					this._capacity = value;
					this.SendPropertyChanged("capacity");
					this.OncapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_status", DbType="NVarChar(50)")]
		public string ship_status
		{
			get
			{
				return this._ship_status;
			}
			set
			{
				if ((this._ship_status != value))
				{
					this.Onship_statusChanging(value);
					this.SendPropertyChanging();
					this._ship_status = value;
					this.SendPropertyChanged("ship_status");
					this.Onship_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_reg_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> ship_reg_time
		{
			get
			{
				return this._ship_reg_time;
			}
			set
			{
				if ((this._ship_reg_time != value))
				{
					this.Onship_reg_timeChanging(value);
					this.SendPropertyChanging();
					this._ship_reg_time = value;
					this.SendPropertyChanged("ship_reg_time");
					this.Onship_reg_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="NVarChar(200)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="NVarChar(50)")]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(50)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orderT")]
	public partial class orderT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Listid;
		
		private int _order_id1;
		
		private string _orderNumber;
		
		private System.Nullable<int> _passenger_id;
		
		private System.Nullable<int> _ship_id;
		
		private string _order_status;
		
		private string _star_location;
		
		private string _end_location;
		
		private string _ship_locetion;
		
		private System.Nullable<System.DateTime> _start_time;
		
		private System.Nullable<System.DateTime> _end_time;
		
		private System.Nullable<decimal> _total_price;
		
		private string _payment_status;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnListidChanging(int value);
    partial void OnListidChanged();
    partial void Onorder_id1Changing(int value);
    partial void Onorder_id1Changed();
    partial void OnorderNumberChanging(string value);
    partial void OnorderNumberChanged();
    partial void Onpassenger_idChanging(System.Nullable<int> value);
    partial void Onpassenger_idChanged();
    partial void Onship_idChanging(System.Nullable<int> value);
    partial void Onship_idChanged();
    partial void Onorder_statusChanging(string value);
    partial void Onorder_statusChanged();
    partial void Onstar_locationChanging(string value);
    partial void Onstar_locationChanged();
    partial void Onend_locationChanging(string value);
    partial void Onend_locationChanged();
    partial void Onship_locetionChanging(string value);
    partial void Onship_locetionChanged();
    partial void Onstart_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onstart_timeChanged();
    partial void Onend_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onend_timeChanged();
    partial void Ontotal_priceChanging(System.Nullable<decimal> value);
    partial void Ontotal_priceChanged();
    partial void Onpayment_statusChanging(string value);
    partial void Onpayment_statusChanged();
    #endregion
		
		public orderT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Listid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Listid
		{
			get
			{
				return this._Listid;
			}
			set
			{
				if ((this._Listid != value))
				{
					this.OnListidChanging(value);
					this.SendPropertyChanging();
					this._Listid = value;
					this.SendPropertyChanged("Listid");
					this.OnListidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id1", DbType="Int NOT NULL")]
		public int order_id1
		{
			get
			{
				return this._order_id1;
			}
			set
			{
				if ((this._order_id1 != value))
				{
					this.Onorder_id1Changing(value);
					this.SendPropertyChanging();
					this._order_id1 = value;
					this.SendPropertyChanged("order_id1");
					this.Onorder_id1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderNumber", DbType="NVarChar(50)")]
		public string orderNumber
		{
			get
			{
				return this._orderNumber;
			}
			set
			{
				if ((this._orderNumber != value))
				{
					this.OnorderNumberChanging(value);
					this.SendPropertyChanging();
					this._orderNumber = value;
					this.SendPropertyChanged("orderNumber");
					this.OnorderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passenger_id", DbType="Int")]
		public System.Nullable<int> passenger_id
		{
			get
			{
				return this._passenger_id;
			}
			set
			{
				if ((this._passenger_id != value))
				{
					this.Onpassenger_idChanging(value);
					this.SendPropertyChanging();
					this._passenger_id = value;
					this.SendPropertyChanged("passenger_id");
					this.Onpassenger_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_id", DbType="Int")]
		public System.Nullable<int> ship_id
		{
			get
			{
				return this._ship_id;
			}
			set
			{
				if ((this._ship_id != value))
				{
					this.Onship_idChanging(value);
					this.SendPropertyChanging();
					this._ship_id = value;
					this.SendPropertyChanged("ship_id");
					this.Onship_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_status", DbType="NVarChar(50)")]
		public string order_status
		{
			get
			{
				return this._order_status;
			}
			set
			{
				if ((this._order_status != value))
				{
					this.Onorder_statusChanging(value);
					this.SendPropertyChanging();
					this._order_status = value;
					this.SendPropertyChanged("order_status");
					this.Onorder_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_star_location", DbType="NVarChar(255)")]
		public string star_location
		{
			get
			{
				return this._star_location;
			}
			set
			{
				if ((this._star_location != value))
				{
					this.Onstar_locationChanging(value);
					this.SendPropertyChanging();
					this._star_location = value;
					this.SendPropertyChanged("star_location");
					this.Onstar_locationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_location", DbType="NVarChar(255)")]
		public string end_location
		{
			get
			{
				return this._end_location;
			}
			set
			{
				if ((this._end_location != value))
				{
					this.Onend_locationChanging(value);
					this.SendPropertyChanging();
					this._end_location = value;
					this.SendPropertyChanged("end_location");
					this.Onend_locationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ship_locetion", DbType="NVarChar(255)")]
		public string ship_locetion
		{
			get
			{
				return this._ship_locetion;
			}
			set
			{
				if ((this._ship_locetion != value))
				{
					this.Onship_locetionChanging(value);
					this.SendPropertyChanging();
					this._ship_locetion = value;
					this.SendPropertyChanged("ship_locetion");
					this.Onship_locetionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> start_time
		{
			get
			{
				return this._start_time;
			}
			set
			{
				if ((this._start_time != value))
				{
					this.Onstart_timeChanging(value);
					this.SendPropertyChanging();
					this._start_time = value;
					this.SendPropertyChanged("start_time");
					this.Onstart_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> end_time
		{
			get
			{
				return this._end_time;
			}
			set
			{
				if ((this._end_time != value))
				{
					this.Onend_timeChanging(value);
					this.SendPropertyChanging();
					this._end_time = value;
					this.SendPropertyChanged("end_time");
					this.Onend_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_price", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> total_price
		{
			get
			{
				return this._total_price;
			}
			set
			{
				if ((this._total_price != value))
				{
					this.Ontotal_priceChanging(value);
					this.SendPropertyChanging();
					this._total_price = value;
					this.SendPropertyChanged("total_price");
					this.Ontotal_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_status", DbType="NVarChar(50)")]
		public string payment_status
		{
			get
			{
				return this._payment_status;
			}
			set
			{
				if ((this._payment_status != value))
				{
					this.Onpayment_statusChanging(value);
					this.SendPropertyChanging();
					this._payment_status = value;
					this.SendPropertyChanged("payment_status");
					this.Onpayment_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ordernews")]
	public partial class ordernews : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _news_id;
		
		private string _headText;
		
		private System.Nullable<int> _Client_id;
		
		private System.Nullable<int> _Driver_id;
		
		private string _message;
		
		private string _message_type;
		
		private System.Nullable<System.DateTime> _send_time;
		
		private string _read_status;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnews_idChanging(int value);
    partial void Onnews_idChanged();
    partial void OnheadTextChanging(string value);
    partial void OnheadTextChanged();
    partial void OnClient_idChanging(System.Nullable<int> value);
    partial void OnClient_idChanged();
    partial void OnDriver_idChanging(System.Nullable<int> value);
    partial void OnDriver_idChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    partial void Onmessage_typeChanging(string value);
    partial void Onmessage_typeChanged();
    partial void Onsend_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onsend_timeChanged();
    partial void Onread_statusChanging(string value);
    partial void Onread_statusChanged();
    #endregion
		
		public ordernews()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int news_id
		{
			get
			{
				return this._news_id;
			}
			set
			{
				if ((this._news_id != value))
				{
					this.Onnews_idChanging(value);
					this.SendPropertyChanging();
					this._news_id = value;
					this.SendPropertyChanged("news_id");
					this.Onnews_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_headText", DbType="NVarChar(255)")]
		public string headText
		{
			get
			{
				return this._headText;
			}
			set
			{
				if ((this._headText != value))
				{
					this.OnheadTextChanging(value);
					this.SendPropertyChanging();
					this._headText = value;
					this.SendPropertyChanged("headText");
					this.OnheadTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_id", DbType="Int")]
		public System.Nullable<int> Client_id
		{
			get
			{
				return this._Client_id;
			}
			set
			{
				if ((this._Client_id != value))
				{
					this.OnClient_idChanging(value);
					this.SendPropertyChanging();
					this._Client_id = value;
					this.SendPropertyChanged("Client_id");
					this.OnClient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Driver_id", DbType="Int")]
		public System.Nullable<int> Driver_id
		{
			get
			{
				return this._Driver_id;
			}
			set
			{
				if ((this._Driver_id != value))
				{
					this.OnDriver_idChanging(value);
					this.SendPropertyChanging();
					this._Driver_id = value;
					this.SendPropertyChanged("Driver_id");
					this.OnDriver_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="NVarChar(255)")]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this.OnmessageChanging(value);
					this.SendPropertyChanging();
					this._message = value;
					this.SendPropertyChanged("message");
					this.OnmessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message_type", DbType="NVarChar(50)")]
		public string message_type
		{
			get
			{
				return this._message_type;
			}
			set
			{
				if ((this._message_type != value))
				{
					this.Onmessage_typeChanging(value);
					this.SendPropertyChanging();
					this._message_type = value;
					this.SendPropertyChanged("message_type");
					this.Onmessage_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_send_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> send_time
		{
			get
			{
				return this._send_time;
			}
			set
			{
				if ((this._send_time != value))
				{
					this.Onsend_timeChanging(value);
					this.SendPropertyChanging();
					this._send_time = value;
					this.SendPropertyChanged("send_time");
					this.Onsend_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_read_status", DbType="NVarChar(50)")]
		public string read_status
		{
			get
			{
				return this._read_status;
			}
			set
			{
				if ((this._read_status != value))
				{
					this.Onread_statusChanging(value);
					this.SendPropertyChanging();
					this._read_status = value;
					this.SendPropertyChanged("read_status");
					this.Onread_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private string _password;
		
		private string _email;
		
		private string _Phone;
		
		private string _photo;
		
		private string _Status;
		
		private string _UserSatus;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnphotoChanging(string value);
    partial void OnphotoChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnUserSatusChanging(string value);
    partial void OnUserSatusChanged();
    #endregion
		
		public users()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(50)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="NVarChar(255)")]
		public string photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this.OnphotoChanging(value);
					this.SendPropertyChanging();
					this._photo = value;
					this.SendPropertyChanged("photo");
					this.OnphotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserSatus", DbType="NVarChar(50)")]
		public string UserSatus
		{
			get
			{
				return this._UserSatus;
			}
			set
			{
				if ((this._UserSatus != value))
				{
					this.OnUserSatusChanging(value);
					this.SendPropertyChanging();
					this._UserSatus = value;
					this.SendPropertyChanged("UserSatus");
					this.OnUserSatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
